### ISSUE TITLE
There's no code yet.

### ISSUE THREAD

**Issue by MisterMonocle** [MasterRain/Waddle#2]
Guys.

Guys there's no code yet.

Guys we need some code.

Guys.

**Comment by MaryLikesCats** [comment]
<html>
</html>

**Comment by PartyLines** [comment]
Adding Code:
Zpv kvtu mptu uif hbnf.

**Comment by MisterMonocle** [comment]
... Uh, care to translate?

**Comment by MisterMonocle** [comment]
Just gonna remove this because it's not that useful.
